import * as React from "react";

import type { NextPage } from "next";
import Head from "next/head";

//components
import Header from "../components/Header";
import ProductsAndFilter from "../components/ProductsAndFilter";

const Home: NextPage = () => {
  return (
    <div className="p-5 ">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col">
        <Header />
        <ProductsAndFilter />
      </main>
    </div>
  );
};

export default Home;
